spring:
     datasource:
        url: jdbc:mysql://192.168.1.12:3306/stock
        username: stock
        password: 123456
     jpa:
        database: mysql
        show-sql: true

        hibernate:
               ddl-auto: create

        properties:
           hibernate:
                   dialect: org.hibernate.dialect.MySQL5Dialect
